### ISSUE TITLE
can't run on ubuntu server

### ISSUE THREAD

**Issue by 5ilvers** [sqshq/sampler#2]
I get this on ubuntu server 18.04
```
panic: oto: ALSA error: No such file or directory

goroutine 1 [running]:
github.com/sqshq/sampler/asset.NewAudioPlayer(0x0)
	/home/sqshq/go/src/github.com/sqshq/sampler/asset/player.go:24 +0x188
main.main()
	/home/sqshq/go/src/github.com/sqshq/sampler/main.go:86 +0xf0
```

**Comment by arnocornette** [comment]
For oto(the music player used in this program), you have to install this dependency: `apt install libasound2-dev`

After that try running again.

@sqshq  Maybe you can do a better way of handling the error at player.go:24 instead of panicing, maybe then just don't play any sound? I could create a PR for it if you want.

**Comment by drozdowsky** [comment]
I am also interested in running this without ALSA.
@sqshq please consider, thank you :)

**Comment by 5ilvers** [comment]
I tried `apt install libasound2-dev` didn't get rid of the error

and yes, I agree with @drozdowsky, i wanted to run it without sound, too.

**Comment by sqshq** [comment]
Thank you for reporting this, guys. I'll fix it.

**Comment by sqshq** [comment]
`1.0.1` was released, the fix for this issue included. Could you please update Sampler and try again?

`sudo wget https://github.com/sqshq/sampler/releases/download/v1.0.1/sampler-1.0.1-linux-amd64 -O /usr/local/bin/sampler`

**Comment by mwaddoups** [comment]
This fixes the issue for me on ubuntu server - thanks for the fix!

It might be worth updating the readme to reflect the new version now that it works - and maybe add a note about the prereqs.

**Comment by 5ilvers** [comment]
can confirm, fixed the issue for me too! Thanks for the quick response!
