### ISSUE TITLE
Can sampler be used for git progress?

### ISSUE THREAD

**Issue by psprint** [sqshq/sampler#21]
Can you use sampler to visualize git clone progress?

**Comment by sqshq** [comment]
I guess the answer is yes. If you can get somehow the current progress value (e.g. in percentage) with a shell command, then you can visualize it as a progress bar using the [gauge component](https://github.com/sqshq/sampler#gauge)

**Comment by psprint** [comment]
So I would have to keep the git process running in background while somehow querying it for the values at the same time?

**Comment by alexeyten** [comment]
Isn't git report clone progress itself?

**Comment by psprint** [comment]
Yes it does. So the process should be ran inside of the sampler? Piped to some script that would preprocess its output for the sampler? I might already have such a script ready: https://github.com/zdharma/zplugin/blob/master/git-process-output.zsh, its current output looks like that: https://asciinema.org/a/ftFkAnKnStvBVsDHbwMHy2ZgT. I wonder if sampler can do something more fancy?
