### ISSUE TITLE
Unicode characters not rendering properly in WSL

### ISSUE THREAD

**Issue by bakeiro** [sqshq/sampler#33]
Hi there, nice product btw

When I execute sampler with a sample config.yml file, the charts display a '?' inside a square where should be a point or a line to display the chart properly.

I guess this should be because my computer doesn't have the font, or the correct character to display.

Enviroment:
Ubuntu 18.04.2 LTS
Executing Ubuntu from windows throught WSL (not virtual machine!)

**Comment by sqshq** [comment]
Hi @bakeiro,
Could you please attach the screenshot and and you config file?

Thank you.

**Comment by bakeiro** [comment]
Sure!
img: https://imgur.com/a/QiUrVD3
config (it's your example config, so I guess has nothing to do but here it is)

### Config
runcharts:
  - title: Search engine response time
    rate-ms: 500        # sampling rate, default = 1000
    scale: 2            # number of digits after sample decimal point, default = 1
    legend:
      enabled: true     # enables item labels, default = true
      details: false    # enables item statistics: cur/min/max/dlt values, default $    items:
      - label: GOOGLE
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
        color: 178      # 8-bit color number, default one is chosen from a pre-defi$      - label: YAHOO
        sample: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
      - label: BING
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com

sparklines:
  - title: CPU usage
    rate-ms: 200
    scale: 0
    sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
  - title: Free memory pages
    rate-ms: 200
    scale: 0
    sample: memory_pressure | grep 'Pages free' | awk '{print $3}'

barcharts:
  - title: Local network activity
    rate-ms: 500        # sampling rate, default = 1000
    scale: 0            # number of digits after sample decimal point, default = 1
    items:
      - label: UDP bytes in
        sample: nettop -J bytes_in -l 1 -m udp | awk '{sum += $4} END {print sum}'
      - label: UDP bytes out
        sample: nettop -J bytes_out -l 1 -m udp | awk '{sum += $4} END {print sum}'
      - label: TCP bytes in
        sample: nettop -J bytes_in -l 1 -m tcp | awk '{sum += $4} END {print sum}'
      - label: TCP bytes out
        sample: nettop -J bytes_out -l 1 -m tcp | awk '{sum += $4} END {print sum}'

**Comment by sqshq** [comment]
Oh, I see what are you talking about. 

I'm afraid it's not something we can fix on the Sampler's side. As far as I can see, currently WSL has issues with unicode characters rendering - there is no font-fallback support there.

https://github.com/microsoft/terminal/issues/306
https://github.com/microsoft/terminal/issues/190

Since font-fallback is not available, you might still have a font which supports currently used characters, you can try to find it manually

**Comment by amazingant** [comment]
@bakeiro: If you're willing to try another terminal emulator, I've had pretty good luck using [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab) with Courier New or Consolas (the font used by the default Ubuntu terminal). Aside from bar charts, everything looks fine in [cmder](https://cmder.net/) (takes a little more setup to get WSL working) if you can't use Windows Terminal.

Here's a screenshot of Sampler running in Windows Terminal with Courier New:

![image](https://user-images.githubusercontent.com/1761309/62785076-d77d9f00-ba8d-11e9-9e4d-0c6bdb3216e7.png)

**Comment by sqshq** [comment]
Closing, since the solution is found and we can't see how it can be fixed on Sampler's side

**Comment by DeathError** [comment]
> Closing, since the solution is found and we can't see how it can be fixed on Sampler's side

Thanks for the answer. I checked some more system on WSL everything repeats . May report to https://github.com/microsoft/WSL/issues ?
