### ISSUE TITLE
Some problems about using software in centos 7

### ISSUE THREAD

**Issue by jiangzhikele** [sqshq/sampler#35]
1、barcharts:
    items:
      - label: UDP bytes in
        sample: nettop -J bytes_in -l 1 -m udp | awk '{sum += $4} END {print sum}'
Nettop is a command in mac. Can CentOS now use commands similar to this function to help? Thanks
2、asciiboxes
About the asciiboxes option。Whether I use it on the Mac or in centos, it doesn't show up. I'm wondering if there are additional steps that I haven't done, such as the requirement for date format. Seek your help。thanks
![1565322972675](https://user-images.githubusercontent.com/38905258/62753168-f0da1780-ba9c-11e9-97a4-e13f2a499064.jpg)
![1565323006200](https://user-images.githubusercontent.com/38905258/62753169-f3d50800-ba9c-11e9-915d-a63a0763a621.jpg)

**Comment by sqshq** [comment]
Hello. I'm pretty sure there is centos alternative, you can search for it on the web.
Regarding the date asciibox. What is the output of `env TZ=CST-8 date` command (without sampler)?

**Comment by LiuZhangshu** [comment]
@jiangzhikele I write a shell to realize the fuction,but not so powerful . If there is any other solution, please let me know

upload :
```shell 
#!/bin/bash
up_time1=`ifconfig enp34s0 | grep "TX packets .*bytes" | awk '{print $5}'`
sleep 1
up_time2=`ifconfig enp34s0 | grep "TX packets .*bytes" | awk '{print $5}'`
up_time=`expr $up_time2 - $up_time1`
up_time=`expr $up_time / 1024`
echo $up_time
```
download
```shell
down_time1=`ifconfig enp34s0 | grep "RX packets .*bytes" | awk '{print $5}'`
sleep 1
down_time2=`ifconfig enp34s0 | grep "RX packets .*bytes" | awk '{print $5}'`
down_time=`expr $down_time2 - $down_time1`
down_time=`expr $down_time / 1024`
echo $down_time
```
