### ISSUE TITLE
getPlatformStoragePath won't find my $HOME

### ISSUE THREAD

**Issue by letompouce** [sqshq/sampler#4]
(You make a commit, 8 hours after that someone complains about it. Internet is wild.)

In `metadata/storage.go`, the [`getPlatformStoragePath`](https://github.com/sqshq/sampler/blob/d5e7d72a6caf7bfc7e1c30554eda7e2ecc8cf58f/metadata/storage.go#L30-L32) function is unable to find my `$HOME`:

`2019/08/03 11:45:28 Failed to init storage: mkdir /.config: permission denied`

`$HOME` is properly set and available in the environment variables.

I'm not a Go guy, but [this](https://github.com/golang/go/issues/31070) may be related.

Thanks!

**Comment by sqshq** [comment]
`1.0.1` was released, the fix for this issue included. Could you please update Sampler and try again?

`sudo wget https://github.com/sqshq/sampler/releases/download/v1.0.1/sampler-1.0.1-linux-amd64 -O /usr/local/bin/sampler`

**Comment by letompouce** [comment]
It successfully created `$HOME/.config/Sampler/statistics.yml`, thanks!
