### ISSUE TITLE
Running sampler on catalina prompts alert...

### ISSUE THREAD

**Issue by crewshin** [sqshq/sampler#40]
------------- alert ------------------
“sampler-1.0.2-darwin-amd64” can’t be opened because its integrity cannot be verified.

This software needs to be updated. Contact the developer for more information.

Move to Trash | Cancel
 ------------- end alert --------------

**Comment by sqshq** [comment]
Hi @crewshin,
Is this solving your issue? https://github.com/fastlane/fastlane/issues/14860

**Comment by crewshin** [comment]
Ah! Yes it does and I've run into this before.

One caveat though... clicking open anyway doesn't work for some reason. You have to change another system preference about being able to navigate system dialogs with your keyboard to be able to tab to that same button, just so you can click it. Silly.

Thanks

**Comment by geoffreywiseman** [comment]
FWIW, this process would be smoother if there were a notarized version so that I don't have to make an exception. I know that's more work for you, so I understand if you don't want to go that path.
