### ISSUE TITLE
Compilation error for ARM architecture

### ISSUE THREAD

**Issue by andrejtad** [sqshq/sampler#48]
```
src/github.com/sqshq/sampler$ GOOS=linux GOARCH=arm go build
# github.com/hajimehoshi/oto
../../hajimehoshi/oto/context.go:69:12: undefined: newDriver
```

**Comment by sqshq** [comment]
Yes, the issue is know and related only to cross-compilation, not compilation on ARM itself:
https://github.com/sqshq/sampler/issues/5#issuecomment-519174316

Right now I can't see any solution other than get rid of Oto player

**Comment by sqshq** [comment]
Closed as duplicate, related to Oto player issues
