### ISSUE TITLE
Cannot run sampler on MacOS Catalina [10.15 Beta (19A558d)]

### ISSUE THREAD

**Issue by xoores** [sqshq/sampler#65]
When I try to run sampler from shell (both ZSH and BASH) I get an error popup saying that "Application sampler-1.0.3-darwin-amd64 cannot be opened, because its identity cannot be verified".

I suspect that it has to do something with Catalinas security improvements/enforcement.

**Comment by xoores** [comment]
Just updated to 10.15 Beta (19A573a), still the same.

**Comment by sqshq** [comment]
Please see https://github.com/sqshq/sampler/issues/40

**Comment by crewshin** [comment]
Actually that does NOT solve the issue. I'm embarrassed that I haven't followed back up with that issue. Long story not worth getting into here however.

Still does not run on Catalina here.

**Comment by xoores** [comment]
For me the issue moved a little bit - I can start the sampler (using provided sample config), however it stops working in cca 5 seconds:

<img width="1282" alt="screenshot" src="https://user-images.githubusercontent.com/2182467/65835324-3bca1b80-e2e5-11e9-86a3-6f4c72bf8a09.png">

**Comment by sqshq** [comment]
Guys, thank you for reporting this.
I'll try to reproduce it once Catalina is finally released in October

**Comment by methodx** [comment]
@sqshq upgraded to Catalina, faced issue. Solution is to allow run sampler from System Preferences -> Security & Privacy.

**Comment by crewshin** [comment]
Also fixed for me on Catalina. The recommended solution did not work on earlier catalina beta's fyi.

**Comment by sqshq** [comment]
same here, I clean installed Catalina, did `brew cask install sampler` and started without any problem

please let me know if you have an issue on the release version

**Comment by itbj** [comment]
Same problem. System Preferences -> Security & Privacy. OK to run.
