### ISSUE TITLE
Feature request - Multiple display "pages"

### ISSUE THREAD

**Issue by deef0000dragon1** [sqshq/sampler#67]
Would it be possible to add some form of pages that can be switched between? Similar to how a security camera system has multiple cameras/ camera groupings that it flips through.

If you would have it if i made it, I would love to work on this myself.

**Comment by deef0000dragon1** [comment]
Possibly an additional request, but also possibly required to make it actually work; The ability to define regions that other things can go into.

**Comment by deef0000dragon1** [comment]
An easier way to do it, though not the cleanest might be to add a new key "displaytime" to the base. Then, taking in several config files, you can display each for the display time, then switch to the next in the order. 

I would have preferred to make it a more recursive yaml file, but recursive yaml/json are a pain in go, and might have had to be breaking for current configs.

**Comment by sqshq** [comment]
Hi @deef0000dragon1,
Thank you for the suggestion, but in this case I would prefer to not complicate the application with this feature. I'd like to keep Sampler simple, especially when the functionality can be more organically integrated into a terminal emulator or multiplexer

**Comment by deef0000dragon1** [comment]
simple from a user/usage perspective or from a code perspective?

**Comment by sqshq** [comment]
Both, I just don't want to complicate anything, including the code, configuration and documentation with features which from my perspective won't be used very often. Also switching "tabs" on schedule can be considered as terminal responsibility, and I guess can be scripted there

I might be mistaken, so we can keep this feature request open for a while if you'd like. If someone else will be interested, it would make sense to implement that
