### ISSUE TITLE
Windows version in chocolatey

### ISSUE THREAD

**Issue by rizickus** [sqshq/sampler#75]
Hi,
Any plans to publish windows executables over chocolatey?

**Comment by sqshq** [comment]
Hi @rizickus,
I'm not a windows users myself, so there is no plans from my side. You are welcome to help with it, if you'd like

**Comment by digitalcoyote** [comment]
I'd be willing to create/maintain a chocolatey package if there is interest.

**Comment by EliteCodexer** [comment]
> 
> 
> I'd be willing to create/maintain a chocolatey package if there is interest.

Yes please.

**Comment by digitalcoyote** [comment]
Getting started on a package before work this morning. I will probably have it submitted by the end of my lunch. It can take ~2 weeks or more to go through moderation depending on how busy the moderators are (moderation is a volunteer effort).
