### ISSUE TITLE
License is incomplete 

### ISSUE THREAD

**Issue by Sivat394** [sqshq/sampler#8]
Use Limitation. The license granted above allows use by up to the
number of users per entity set forth above (the "Use Limitation"). For
determining the number of users, "you" includes all affiliates,
meaning legal entities controlling, controlled by, or under common
control with you. If you exceed the Use Limitation, your use is
subject to payment of Licensor’s then-current list price for licenses.

Because you don't have a listing price for licenses it can only be assumed that the price is in fact 0.00 for extra users.

**Comment by sqshq** [comment]
The price is available on the [website](http://sampler.dev/), which is specified in the repository header. Also it should not be a part of the License document itself.
